---
version: 2.1
executorType: docker
containerInfo:
  - image: library/golang
    environment:
      AWS_ACCESS_KEY_ID: 1
      AWS_SECRET_ACCESS_KEY: 1
jobs:
  build:
    workdir: "/go/src/github.com/zencoder/ddbsync"
    steps:
      - checkout
      - restore_cache:
          key: go-mod-cache-{{ checksum "go.sum" }}
      - run:
          name: Download vendored Go dependencies
          command: go mod download
      - save_cache:
          key: go-mod-cache-{{ checksum "go.sum" }}
          paths:
            - /go/pkg/mod
      - run:
          name: Build
          command: make build
      - run:
          name: Test
          command: make test
      - run:
          name: Produce coverage report
          command: make cover
      - store_artifacts:
          path: coverage/
